// React/02-react脚手架/react_staging/src/components/Footer/index.jsx
import React, { Component } from 'react'
import './index.css'

export default class index extends Component {
    render() {
        return (
          <div className="todo-footer">
            <label>
              <input type="checkbox"/>
            </label>
            <span>
              <span>已完成0</span> / 全部2
            </span>
            <button className="btn btn-danger">清除已完成任务</button>
          </div>
        )
    }
}

// VUE2+3/vue2/vue_staging/src/components/footer/Footer.vue
<template>
    <div class="footer">
        <input type="checkbox" name="" id="sum">
        <label for="sum">已完成1 / 全部3</label>
        <button>清除已完成任务</button>
    </div>
</template>

<script>
export default {
    name: 'Footer',

}
</script>

<style scoped>
/* footer */
.footer {
    text-indent: 0.5em;
    height: 36px;
    line-height: 36px;
    position: relative;
}

.footer input {
    margin-right: 15px;
}
</style>
