// React/02-react脚手架/react_staging/06_src_github搜索-pubsub/src/components/Item/index.jsx
import React, { Component } from 'react';

import './index.css'

export default class Item extends Component {
  render() {
    const {userObj} = this.props;
    return (
        <div className="card">
            <a href={userObj.html_url} target="_blank" rel="noreferrer">
              <img alt='profile' src={userObj.avatar_url} style={{width: '100px'}}/>
            </a>
            <p className="card-text">{userObj.login}</p>
        </div>
    )
  }
}

// VUE2+3/vue2/vue_staging/19_src_github搜索案例/components/Item/Item.vue
<template>
    <div class="card" >
        <a :href="user.html_url" target="_blank">
              <img alt='profile' :src="user.avatar_url" style="width: 100px"/>
        </a>
        <p class="card-text">{{user.login}}</p>
    </div>
    
</template>

<script>

export default {
    name: 'Item',
    props: ['user']

}
</script>

<style lang="less" scoped>
/* item */
.card {
    float: left;
    width: 33.333%;
    padding: .75rem;
    margin-bottom: 2rem;
    border: 1px solid #efefef;
    text-align: center;
}

.card > img {
  margin-bottom: .75rem;
  border-radius: 100px;
}

.card-text {
  font-size: 85%;
}
</style>
