// React/02-react脚手架/react_staging/05_src_github搜索案例-axios/src-客户端3000/src/components/Search/index.jsx
import React, { Component } from 'react';
import axios from 'axios'

export default class Search extends Component {
  // 点击搜索的回调
  getUserData = ()=> {
    // 获取输入框的值(连续解构赋值+重命名)
    const {inputKeyWord:{value: keyword}} = this
    // 请求成功前，发送请求前通知App更新状态，isFirst和isLoading
    this.props.updateAppState({isFirst: false, isLoading: true})
    // 发起网络请求(axios)
    axios.get(`http://localhost:3000/api1/search/users?q=${keyword}`)
    .then(
        // 请求成功后，发送请求前通知App更新状态isLoading，保存users
        response => {
          this.props.updateAppState({isLoading: false, users: response.data.items})
        },
        // 请求错误 展示错误
        // 注意这里不要直接存储err，而是错误信息
        error => {
          this.props.updateAppState({isLoading:false,err:error.message})
        }
    )
  }
  render() {
    return (
        <section className='jumbotron'>
          <h3>搜索github用户</h3>
          <div>
            <input ref={(c)=>{this.inputKeyWord = c}} type="text" placeholder='请输入关键词进行搜索'/>
            &nbsp;<button onClick={this.getUserData}>搜索</button>
          </div>
        </section>
    )
  }
}

// VUE2+3/vue2/vue_staging/19_src_github搜索案例/components/Search/Search.vue
<template>
    <section class='jumbotron'>
      <h3>搜索github用户</h3>
      <div>
        <input  type="text" v-model="keyWords" placeholder='请输入关键词进行搜索'/>
        &nbsp;
        <button @click="searchUsers">搜索</button>
      </div>
    </section>
</template>

<script>
import axios from 'axios'

export default {
    name: 'Search',
    data() {
        return {
            keyWords: ''
        }
    },
    methods: {
        // 搜索回调
        searchUsers() {
            // 请求前更新List的数据
			this.$bus.$emit('updateListData',{isLoading:true,errMsg:'',users:[],isFirst:false})
            // 发起网络请求
            axios.get(`https://api.github.com/search/users?q=${this.keyWords}`).then(
                response => {
                    console.log('成功了');
                    // // 触发事件
                    // this.$bus.$emit('getUsers', response.data.items)
                    //请求成功后更新List的数据
					this.$bus.$emit('updateListData',{isLoading:false,errMsg:'',users:response.data.items})
                },
                error => {
                    console.log('失败了',error.message);
                    // 请求后更新List的数据
					this.$bus.$emit('updateListData',{isLoading:false,errMsg:error.message,users:[]})
                }
            )

            
        }
    },
    
}
</script>

<style lang="less" scoped>

</style>
