// React/02-react脚手架/react_staging/07_src_github搜索-fetch/src/components/Search/index.jsx
import React, { Component } from 'react';
import PubSub from 'pubsub-js'

export default class Search extends Component {

  // 点击搜索的回调
  getUserData = async()=> {
    // 获取输入框的值(连续解构赋值+重命名)
    const {inputKeyWord:{value: keyword}} = this
    // 请求成功前，发送请求前通知List更新状态，isFirst和isLoading
    PubSub.publish('githubUsers',{isFirst: false, isLoading: true});

    //发送网络请求---使用fetch发送（未优化）
		/* fetch(`/api1/search/users2?q=${keyword}`).then(
			response => {
				console.log('联系服务器成功了');
				return response.json()
			},
			error => {
				console.log('联系服务器失败了',error);
				return new Promise(()=>{})
			}
		).then(
			response => {console.log('获取数据成功了',response);},
			error => {console.log('获取数据失败了',error);}
		) */

    //发送网络请求---使用fetch发送（优化）
		try {
			const response= await fetch(`/api1/search/users?q=${keyword}`)
			const data = await response.json()
			console.log(data);
			PubSub.publish('githubUsers',{isLoading:false,users:data.items})
		} catch (error) {
			console.log('请求出错',error);
			PubSub.publish('githubUsers',{isLoading:false,err:error.message})
		}
   
  }
  render() {
    return (
        <section className='jumbotron'>
          <h3>搜索github用户</h3>
          <div>
            <input ref={(c)=>{this.inputKeyWord = c}} type="text" placeholder='请输入关键词进行搜索'/>
            &nbsp;<button onClick={this.getUserData}>搜索</button>
          </div>
        </section>
    )
  }
}

// VUE2+3/vue2/vue_staging/19_src_github搜索案例/components/Search/Search.vue
<template>
    <section class='jumbotron'>
      <h3>搜索github用户</h3>
      <div>
        <input  type="text" v-model="keyWords" placeholder='请输入关键词进行搜索'/>
        &nbsp;
        <button @click="searchUsers">搜索</button>
      </div>
    </section>
</template>

<script>
import axios from 'axios'

export default {
    name: 'Search',
    data() {
        return {
            keyWords: ''
        }
    },
    methods: {
        // 搜索回调
        searchUsers() {
            // 请求前更新List的数据
			this.$bus.$emit('updateListData',{isLoading:true,errMsg:'',users:[],isFirst:false})
            // 发起网络请求
            axios.get(`https://api.github.com/search/users?q=${this.keyWords}`).then(
                response => {
                    console.log('成功了');
                    // // 触发事件
                    // this.$bus.$emit('getUsers', response.data.items)
                    //请求成功后更新List的数据
					this.$bus.$emit('updateListData',{isLoading:false,errMsg:'',users:response.data.items})
                },
                error => {
                    console.log('失败了',error.message);
                    // 请求后更新List的数据
					this.$bus.$emit('updateListData',{isLoading:false,errMsg:error.message,users:[]})
                }
            )

            
        }
    },
    
}
</script>

<style lang="less" scoped>

</style>
